### PR TITLE
fix(flock): Use sh compatible syntax.

### PR DESCRIPTION
**Pull request by kacf**
Signed-off-by: Kristian Amlie <kristian.amlie@northern.tech>

### CODE REVIEW

**Review by oleorhagen — APPROVED** [review]
Wow. Did we learn this the hard way?

**Comment by kacf** [comment]
Not the fall-on-our-face way, but [the CI way](https://gitlab.com/Northern.tech/Mender/mender-convert/-/jobs/3545340841). The SHA is not updated in our build integrations yet. 🙂

**Comment by clementperon** [comment]
Haa sorry FDs are per proccess so 9 is good 

What about something like this to avoid hardcoding it
```
lowest_unused_fd () {
    local FD=0
    while [ -e /proc/$$/fd/$FD ]; do
        FD=$((FD+1))
    done
    echo $FD
}
FD=$(lowest_unused_fd)
```

**Comment by kacf** [comment]
9 is the highest that we can use. From "dash" man page:

> The [n] is an optional number between 0 and 9 [...] that refers to a file descriptor.

I don't think it really matters if it's already taken. If it's taken then it means that a file descriptor was being inherited, which is a mistake (a very common mistake in POSIX). A shell process should only need the 0, 1 and 2 file descriptors, so we can freely close the others unless we know that we will need them.

**Pull request merged**
